### ISSUE TITLE
Unknown object modification type: FURN

### ISSUE THREAD

**Issue by claytonaguiar** [praecipitator/ItemAutoTagger#1]
When CWPointLookoutFO4.esm (Fallout 4 Point Lookout) is active in the load order and you try to use ItemAutoTagger, it crashes with the message

RecordException CWPointLookoutFO4.esm => 02044B:CWPointLookoutFO4.esm<AObjectModification>: Unknown object modification type: FURN 

Using default configurations after installation following MOFAM guide.

**Comment by praecipitator** [comment]
Fixed in Mutagen itself
